-- Run AFTER the image files and new categories are deployed to Vercel.
-- Adds 12 items; existing products and prices are not changed.
BEGIN;
INSERT INTO public.products (slug,name,line_one,colour,colour_name,category,image_url,concept,description,supporting,is_active) VALUES
('slc-hoodies-white','SLC Zip Hoodie — White','COMFORT IS MY STANDARD.','#eee9de','White','hoodies','/new-collection/slc-hoodie-white.png',true,'A hooded zip-front layer with drawstrings, front pockets and the SLC monogram. The styling quote describes the mood; the garment carries the logo shown.',ARRAY['For the woman who makes ease look effortless.','She keeps her comfort close and her standards high.']::text[],true),
('slc-hoodies-black','SLC Zip Hoodie — Black','COMFORT IS MY STANDARD.','#171614','Black','hoodies','/new-collection/slc-hoodie-black.png',true,'A hooded zip-front layer with drawstrings, front pockets and the SLC monogram. The styling quote describes the mood; the garment carries the logo shown.',ARRAY['For the woman who makes ease look effortless.','She keeps her comfort close and her standards high.']::text[],true),
('slc-hoodies-brown','SLC Zip Hoodie — Brown','COMFORT IS MY STANDARD.','#4f3428','Brown','hoodies','/new-collection/slc-hoodie-brown.png',true,'A hooded zip-front layer with drawstrings, front pockets and the SLC monogram. The styling quote describes the mood; the garment carries the logo shown.',ARRAY['For the woman who makes ease look effortless.','She keeps her comfort close and her standards high.']::text[],true),
('slc-trousers-white','SLC Wide-Leg Trousers — White','ROOM TO MOVE. SPACE TO BE.','#eee9de','White','trousers','/new-collection/slc-pants-white.png',true,'Wide-leg trousers with a drawstring waist and the SLC monogram. The styling quote describes the mood; the garment carries the logo shown.',ARRAY['For the woman who moves through life on her own terms.','She takes up space without explaining herself.']::text[],true),
('slc-trousers-black','SLC Wide-Leg Trousers — Black','ROOM TO MOVE. SPACE TO BE.','#171614','Black','trousers','/new-collection/slc-pants-black.png',true,'Wide-leg trousers with a drawstring waist and the SLC monogram. The styling quote describes the mood; the garment carries the logo shown.',ARRAY['For the woman who moves through life on her own terms.','She takes up space without explaining herself.']::text[],true),
('slc-trousers-brown','SLC Wide-Leg Trousers — Brown','ROOM TO MOVE. SPACE TO BE.','#4f3428','Brown','trousers','/new-collection/slc-pants-brown.png',true,'Wide-leg trousers with a drawstring waist and the SLC monogram. The styling quote describes the mood; the garment carries the logo shown.',ARRAY['For the woman who moves through life on her own terms.','She takes up space without explaining herself.']::text[],true),
('slc-tops-white','SLC Signature Tank — White','LESS NOISE. MORE ME.','#eee9de','White','tops','/new-collection/slc-top-white.png',true,'A slim-strap, scoop-neck top with the SLC monogram at the chest. The styling quote describes the mood; the garment carries the logo shown.',ARRAY['For the woman who finds confidence in simplicity.','Her presence says enough.']::text[],true),
('slc-tops-black','SLC Signature Tank — Black','LESS NOISE. MORE ME.','#171614','Black','tops','/new-collection/slc-top-black.png',true,'A slim-strap, scoop-neck top with the SLC monogram at the chest. The styling quote describes the mood; the garment carries the logo shown.',ARRAY['For the woman who finds confidence in simplicity.','Her presence says enough.']::text[],true),
('slc-tops-brown','SLC Signature Tank — Brown','LESS NOISE. MORE ME.','#4f3428','Brown','tops','/new-collection/slc-top-brown.png',true,'A slim-strap, scoop-neck top with the SLC monogram at the chest. The styling quote describes the mood; the garment carries the logo shown.',ARRAY['For the woman who finds confidence in simplicity.','Her presence says enough.']::text[],true),
('slc-sunglasses-model-1','SLC Rimless Sunglasses — Champagne','A SOFTER POINT OF VIEW.','#c5aa87','Champagne','sunglasses','/new-collection/sunglasses-model-1.png',true,'Rimless sunglasses with softly tinted lenses and decorative gold-tone arms. The styling quote is editorial, not lettering on the frames.',ARRAY['For the woman who sees possibility everywhere.','She chooses her own perspective.']::text[],true),
('slc-sunglasses-model-2','SLC Wrap Sunglasses — Black','MY PEACE IS PRIVATE.','#161616','Black','sunglasses','/new-collection/sunglasses-model-2.png',true,'Black wrap-style sunglasses with dark lenses and the SLC monogram at the temples. The styling quote is editorial, not lettering on the frames.',ARRAY['For the woman who decides what gets her attention.','Her boundaries look good on her.']::text[],true),
('slc-sunglasses-model-3','SLC Wrap Sunglasses — Brown','UNBOTHERED. ALWAYS.','#643524','Brown','sunglasses','/new-collection/sunglasses-model-3.png',true,'Brown wrap-style sunglasses with tinted lenses and the SLC monogram at the temples. The styling quote is editorial, not lettering on the frames.',ARRAY['For the woman whose confidence needs no audience.','She keeps her outlook warm and her standards clear.']::text[],true)
ON CONFLICT (slug) DO NOTHING;
COMMIT;
